# Generated by Django 3.2.5 on 2022-09-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='makandurateam',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name_member', models.CharField(max_length=100)),
                ('image_member', models.TextField()),
            ],
        ),
    ]
