# Generated by Django 3.2.5 on 2022-09-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newspage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summery', models.TextField()),
                ('content', models.JSONField()),
                ('image', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
